version: '3.3'
services:
  proxy-client:
    image: lgp/proxy
    build: proxy
    ports:
      - "8080:8080"
    environment:
      - MOCK_URL=https://www.lightclientdata.org
#    healthcheck:
#      test: [ "CMD-SHELL", "curl --fail http://localhost:80/health || exit 1" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5

#      - ./data:/home
#      - hermes:/root/.hermes
